name: Tests

on: [push, pull_request]

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        run: |
          sudo apt-get update
          sudo add-apt-repository universe
          sudo apt install luarocks -y
          sudo luarocks install luacheck

      - name: Run Luacheck
        run: luacheck .

  stylua:
    name: StyLua
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.15.2
          args: --check .

  run_tests:
    strategy:
      matrix:
        include:
          - nvim_tag: v0.8.3
          - nvim_tag: v0.9.1

    name: Run tests
    runs-on: ubuntu-22.04
    env:
      NVIM_TAG: ${{ matrix.nvim_tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Neovim and dependencies
        run: |
          bash ./.github/workflows/install_nvim.sh

      - name: Run tests
        run: |
          bash ./run_tests.sh

  release:
    name: release

    if: ${{ github.ref == 'refs/heads/master' }}
    needs:
      - luacheck
      - stylua
      - run_tests
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: oil.nvim
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          tag: stable
          message: "Current stable release: ${{ steps.release.outputs.tag_name }}"
          tag_exists_error: false
          force_push_tag: true
