name: Tests

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selene:
    name: Selene
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --display-style quiet .

  stylua:
    name: StyLua
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.1.0
          args: --check lua tests

  typecheck:
    name: typecheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: mrcjkb/lua-typecheck-action@v0
        with:
          checklevel: Warning
          directories: lua
          configpath: .luarc.json

  run_tests:
    strategy:
      matrix:
        include:
          - nvim_tag: v0.8.3
          - nvim_tag: v0.9.4
          - nvim_tag: v0.10.4
          - nvim_tag: v0.11.0

    name: Run tests
    runs-on: ubuntu-22.04
    env:
      NVIM_TAG: ${{ matrix.nvim_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim and dependencies
        run: |
          bash ./.github/workflows/install_nvim.sh

      - name: Run tests
        run: |
          bash ./run_tests.sh
